(require-package 'switch-window)
;; (require 'switch-window-auto-loads)
;; (global-set-key (kbd "C-x o") 'switch-window)
;; (global-set-key (kbd "C-x 1") 'switch-window-then-delete)
(provide 'init-switch-window)
